name: Validação do Terraform e Cria PR para develop

on:
  push:
    branches:
      - 'feature/**'

jobs:
  validacao-terraform:
    uses: dev-gustaavo/terraform-reusable/.github/workflows/1-validated-terraform-crate-pr-develop.yaml@main
    with:
      pr_branch_name: 'develop'
