name: Aplica o Terraform e Cria o PR para a main

on:
  push:
    branches:
      - develop

jobs:
  apply-terraform:
    uses: dev-gustaavo/terraform-reusable/.github/workflows/2-apply-terraform-create-pr-main.yaml
    with:
      pr_branch_name: 'main'
      terraform_command: |
        $(jq -r '.terraform.apply' aplicacao-infra.json) == 'true' && echo "apply" || echo "destroy"